export const CONVERSATION_STATE = {
  IDLE: "IDLE",
  MAIN_MENU: "MAIN_MENU",
  SELECT_CATEGORY: "SELECT_CATEGORY",
  SELECT_MENU_ITEM: "SELECT_MENU_ITEM",
  SELECT_OPTION: "SELECT_OPTION",
  SELECT_QUANTITY: "SELECT_QUANTITY",
};
